

// Login Constants
export const LOGIN_PATIENT_REQUEST = 'LOGIN_PATIENT_REQUEST';
export const LOGIN_PATIENT_SUCCESS = 'LOGIN_PATIENT_SUCCESS';
export const LOGIN_PATIENT_FAILURE = 'LOGIN_PATIENT_FAILURE';
export const LOGIN_PATIENT_IDLE = 'LOGIN_PATIENT_IDLE';
